# Generated by Django 3.2.7 on 2021-09-17 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_describe', models.CharField(max_length=250, unique=True, verbose_name='订单描述')),
                ('price', models.CharField(max_length=20, verbose_name='订单价格')),
                ('order_start', models.DateTimeField(verbose_name='订单开始时间')),
                ('order_end', models.DateTimeField(verbose_name='订单结束时间')),
                ('qrcode', models.CharField(max_length=50, null=True, unique=True, verbose_name='二维码')),
            ],
            options={
                'verbose_name_plural': '订单设置',
            },
        ),
        migrations.CreateModel(
            name='pay_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type_name', models.CharField(max_length=20, verbose_name='支付方式')),
            ],
            options={
                'verbose_name_plural': '支付方式',
            },
        ),
        migrations.CreateModel(
            name='yuyue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(max_length=20, verbose_name='性别')),
                ('age', models.CharField(max_length=20, verbose_name='年龄')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('id_type', models.CharField(max_length=20, verbose_name='证件类型')),
                ('id_code', models.CharField(max_length=50, verbose_name='证件号')),
                ('yuyue_date', models.DateField(verbose_name='预约日期')),
                ('yuyue_time', models.CharField(max_length=20, verbose_name='预约时间段')),
                ('opr_time', models.DateTimeField(auto_now_add=True, verbose_name='预约提交时间')),
                ('openid', models.CharField(blank=True, max_length=50, verbose_name='预约openid')),
                ('barcode', models.CharField(max_length=50, null=True, unique=True, verbose_name='条码号')),
                ('status', models.CharField(max_length=50, verbose_name='订单状态')),
                ('qrcode', models.CharField(max_length=50, null=True, unique=True, verbose_name='二维码')),
                ('last_opr_time', models.DateTimeField(auto_now=True, verbose_name='最后操作时间')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyue_wx.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name_plural': '样本信息管理',
                'unique_together': {('id_code', 'yuyue_date')},
            },
        ),
        migrations.CreateModel(
            name='wenjuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wenjuan_result', models.CharField(max_length=500, verbose_name='问卷详情')),
                ('wenjuan_time', models.DateTimeField(auto_now_add=True, verbose_name='问卷提交时间')),
                ('yuyue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyue_wx.yuyue', verbose_name='所属样本')),
            ],
            options={
                'verbose_name_plural': '调查问卷管理',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_order_id', models.CharField(max_length=50, null=True, unique=True, verbose_name='付款单编号')),
                ('prepay_id', models.CharField(max_length=50, verbose_name='支付ID')),
                ('pay_amount', models.CharField(max_length=10, verbose_name='支付价格')),
                ('description', models.CharField(max_length=100, verbose_name='订单信息')),
                ('openid', models.CharField(max_length=50, verbose_name='支付openid')),
                ('payment_status', models.CharField(max_length=10, verbose_name='支付状态')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='支付时间')),
                ('yuyue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyue_wx.yuyue', verbose_name='所属样本')),
            ],
            options={
                'verbose_name_plural': '支付管理',
            },
        ),
        migrations.CreateModel(
            name='organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_name', models.CharField(max_length=250, unique=True, verbose_name='机构名称')),
                ('p_organ', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='yuyue_wx.organ', verbose_name='上级机构')),
                ('pay_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyue_wx.pay_type', verbose_name='支付方式')),
            ],
            options={
                'verbose_name_plural': '机构设置',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='organ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyue_wx.organ', verbose_name='所属机构'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyue_wx.pay_type', verbose_name='支付方式'),
        ),
    ]
