# Generated by Django 3.2.7 on 2021-09-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuyue_wx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuyue',
            name='yuyue_type',
            field=models.CharField(default='A', max_length=20, verbose_name='预约项目'),
            preserve_default=False,
        ),
    ]
